### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by ojengwa** [wdm0006/cookiecutter-pipproject#1]
There is a typo in `setup.py`, `line 38`. `depedency` was misspelt.
`depedency_links=dependency_links` should be `dependency_links=dependency_links`

**Comment by wdm0006** [comment]
Thanks Ojengwa, good catch.  Would you like to open a pull request with your change? I can merge it in if so, or make the change directly if not.

**Comment by ojengwa** [comment]
Sure. :)
