### ISSUE TITLE
Incorrect list comprehension

### ISSUE THREAD

**Issue by eccles** [wdm0006/cookiecutter-pipproject#4]
In setup.py the following statement:

dependency_links = [x.strip().replace('git+', '') for x in all_reqs if 'git+' not in x]

seems contradictory. If the list has no items with 'git+' in them why bother to replace 'git+' with ''?

i.e. the 'not' is incorrect. Should it also not be x.startswith('git+')?

**Comment by wdm0006** [comment]
Yep, I think you're right.

If you'd like to submit a PR I can merge it, otherwise I'll fix it when I get a chance, probably in the next day or two.

**Comment by eccles** [comment]
Just fix it when you get the chance as I have no way of testing it presently. Nice template by the way... :-)
