### ISSUE TITLE
Actual tests

### ISSUE THREAD

**Issue by asmodehn** [wdm0006/cookiecutter-pipproject#5]
We should probably have one test example in this template.

Running pytest on it fails (`collected 0 items` -> return status 5) because there is actually no test...

**Comment by wdm0006** [comment]
That is a good idea. Would you be interested in working on that and sending a pull request?

**Comment by asmodehn** [comment]
Did it in https://github.com/wdm0006/cookiecutter-pipproject/pull/6
Not sure what's up with github and the commit author... feel free to edit whatever you need in that PR.
